# <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
# $$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
# <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

# vsota sodih elementov fib zap do 4 mio

def fibonaccijeva_stevila(n=4000000): # n je zgornja meja, ki jo lahko dosežemo
    a, b = 1, 2 # lahko preskočimo 0 in prvo 1
    vsota = 0 # vsota sodih
    while a <= n: # dokler člen ne preseže meje
        if a % 2 == 0:
            vsota += a
        a, b = b, a + b
    return vsota
    

print(fibonaccijeva_stevila())

